export const song_mocks = [
  {
    id: "277d9682-e4ee-4e8f-b3c3-518f2dbff53e",
    title: "orange hues",
    author: "aqualina",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "fluid",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "playground_park",
    natural_environments: null,
    date: "11/4/2024, 11:37:28 PM",
    source: "https://www.youtube.com/watch?v=14ij-aEbhdY",
    sound_source: "musical_instruments"
  },
  {
    id: "c0781c58-c4f7-4271-a829-81eccf055262",
    title: "laminaria",
    author: "geju",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "fluid",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "outdoors",
    natural_environments: null,
    date: "11/5/2024, 8:41:23 PM",
    source: "https://www.youtube.com/watch?v=B7GMfcigQUU",
    sound_source: "hybrid_sources"
  },
  {
    id: "4263c3b5-4c41-4a59-b8f2-b161bf5bd0f1",
    title: "are you even real",
    author: "james blake",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "micro",
    tempo_modulation: "rubato",
    beat_types: "syncopation",
    tempo_range: "slow",
    tempo_complexity: "metric_modulation",
    spatial_context: "enclosed_settings",
    enclosed_settings: "concert_hall",
    open_air: null,
    natural_environments: null,
    date: "11/5/2024, 8:49:45 PM",
    source: "https://www.youtube.com/watch?v=_AYrcgkqMUE",
    sound_source: "musical_instruments"
  },
  {
    id: "8dc7609f-af4c-4b22-95fc-789adb081d2c",
    title: "move",
    author: "adam port feat malachiii",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "macro",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "medium",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:11:52 PM",
    source: "https://www.youtube.com/watch?v=95dB-ObZ7Ho",
    sound_source: "synthetic_sources"
  },
  {
    id: "47397d93-bb57-48e2-a9da-3fc9a87114bf",
    title: "essert romance",
    author: "dada disco",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "macro",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "polytemporal",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:16:02 PM",
    source: "https://www.youtube.com/watch?v=Ug7V94GICoQ",
    sound_source: "synthetic_sources"
  },
  {
    id: "dd56ce2a-0000-4027-8aca-14344c9288f7",
    title: "simon says",
    author: "refilled",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "macro",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "medium",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:17:57 PM",
    source: "https://www.youtube.com/watch?v=ychh3FpsXJk",
    sound_source: "synthetic_sources"
  },
  {
    id: "f13db0f0-479e-4f81-bb05-297715143f38",
    title: "dreamers wake",
    author: "rival consoles",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "fluid",
    tempo_modulation: "rubato",
    beat_types: "syncopation",
    tempo_range: "medium",
    tempo_complexity: "metric_modulation",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:21:58 PM",
    source: "https://www.youtube.com/watch?feature=shared&v=dVAQO6Fs2f0",
    sound_source: "hybrid_sources"
  },
  {
    id: "ec648664-61da-42c5-8a33-97af10321ff8",
    title: "the lost girls",
    author: "flying lotus",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "recursive",
    tempo_modulation: "rubato",
    beat_types: "complex",
    tempo_range: "medium",
    tempo_complexity: "metric_modulation",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "outdoors",
    natural_environments: null,
    date: "11/5/2024, 9:32:13 PM",
    source: "https://www.youtube.com/watch?v=r7MEZYxcDik",
    sound_source: "musical_instruments"
  },
  {
    id: "33a8110e-6308-47af-b455-9cbbe5ea2745",
    title: "stranger things",
    author: "bacao rhythm  steel band",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "fluid",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:35:57 PM",
    source: "https://www.youtube.com/watch?feature=shared&v=wHPlI69KF9I",
    sound_source: "musical_instruments"
  },
  {
    id: "b97d7de5-94ee-4def-83e9-08b9ae778163",
    title: "del oro",
    author: "floating points",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "macro",
    tempo_modulation: "rubato",
    beat_types: "syncopation",
    tempo_range: "medium",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:40:41 PM",
    source: "https://www.youtube.com/watch?feature=shared&v=7iedUG5Kpis",
    sound_source: "synthetic_sources"
  },
  {
    id: "4f1959c3-fc7e-4dc1-bd02-677ca78ec758",
    title: "persona",
    author: "rival consoles",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "macro",
    tempo_modulation: "static_tempo",
    beat_types: "complex",
    tempo_range: "medium",
    tempo_complexity: "metric_modulation",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:43:09 PM",
    source: "https://www.youtube.com/watch?feature=shared&v=niiUkcLpwXY",
    sound_source: "synthetic_sources"
  },
  {
    id: "34e536e2-5a56-4f1d-af54-95fcfcad1b0b",
    title: "stone in focus",
    author: "aphex twin",
    user_email: "syntia.birgele@gmail.com",
    rhytmic_scale: "fluid",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "constant",
    spatial_context: "open_air",
    enclosed_settings: null,
    open_air: "rooftop_pier",
    natural_environments: null,
    date: "11/5/2024, 9:47:15 PM",
    source: "https://www.youtube.com/watch?v=q86g1aop6a8",
    sound_source: "musical_instruments"
  },
  {
    id: "1910f536-5488-4ebc-9a37-845e033df5b2",
    title: "outer space",
    author: "chloe",
    user_email: null,
    rhytmic_scale: "fluid",
    tempo_modulation: "static_tempo",
    beat_types: "even",
    tempo_range: "slow",
    tempo_complexity: "constant",
    spatial_context: "natural_environments",
    enclosed_settings: null,
    open_air: null,
    natural_environments: "environmental",
    date: "11/6/2024, 2:37:15 PM",
    source: "https://www.youtube.com/watch?v=hQDgWCj8HgU",
    sound_source: "synthetic_sources"
  },
  {
    id: "61d6c9d1-3c6f-483d-98fc-76866c94199e",
    title: "moonscape",
    author: "chloe",
    user_email: null,
    rhytmic_scale: "macro",
    tempo_modulation: "static_tempo",
    beat_types: "complex",
    tempo_range: "medium",
    tempo_complexity: "polytemporal",
    spatial_context: "natural_environments",
    enclosed_settings: null,
    open_air: null,
    natural_environments: "environmental",
    date: "11/6/2024, 2:41:55 PM",
    source: "https://www.youtube.com/watch?feature=shared&v=lH49wDy03JI",
    sound_source: "synthetic_sources"
  }
];